FROM quay.io/aptible/debian:wheezy

# Define PostgreSQL version for shared scripts
ENV PG_VERSION <%= ENV.fetch 'POSTGRES_VERSION' %>
ENV POSTGIS_VERSION <%= ENV.fetch 'POSTGIS_VERSION' %>

# cf. docker-library/postgres: explicitly create the user so uid and gid are consistent.
RUN groupadd -r postgres && useradd -r -g postgres postgres

# Temporary workaround for host-container user conflicts on Linux Kernel >= 3.15
# See https://github.com/docker/docker/issues/6345 for details.
RUN ln -s -f /bin/true /usr/bin/chfn

# Install some helpers we'll need
RUN apt-install locales wget unzip sudo pwgen \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

# And now install Postgres from its own repos
ADD templates/etc/apt /etc/apt


# The package names below are anchored, becuase they're interpreted by apt as regexes
# (because they contain "."), which can result in undesired packages being installed if
# we don't update the PG and PostGIS versions properly, e.g.:
# $ sudo apt-get install -y postgresql-9.5-postgis-2.1
# Reading package lists... Done
# Building dependency tree
# Reading state information... Done
# Note, selecting 'postgresql-9.5-postgis-2.1-scripts' for regex 'postgresql-9.5-postgis-2.1'
# 0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8 \
 && apt-get update \
 && apt-get -y install postgresql-common \
 && sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf \
 && apt-get -y install \
    "^postgresql-${PG_VERSION}\$" \
    "^postgresql-client-${PG_VERSION}\$" \
    "^postgresql-contrib-${PG_VERSION}\$" \
    "^postgresql-${PG_VERSION}-postgis-${POSTGIS_VERSION}\$" \
 && rm -rf /var/lib/apt/lists/*

ENV CONF_DIRECTORY /etc/postgresql/$PG_VERSION
ADD templates/etc/postgresql/PG_VERSION $CONF_DIRECTORY

ENV DATA_DIRECTORY /var/db
RUN mkdir $DATA_DIRECTORY && chown -R postgres $DATA_DIRECTORY

ADD bin/run-database.sh /usr/bin/
ADD bin/utilities.sh /usr/bin/

ADD $PG_VERSION/test /tmp/test
ADD test /tmp/test
RUN bats /tmp/test

VOLUME ["$DATA_DIRECTORY"]
EXPOSE 5432
ENTRYPOINT ["/usr/bin/run-database.sh"]
