name: Release

on:
  push:
    branches:
      - "master"

jobs:
  build:
    strategy:
      matrix:
        postgres: ['9.5','9.5-contrib','9.5-pg_cron','9.6','9.6-contrib','10','10-contrib','10-pg_cron','11','11-contrib','12','12-contrib','13','13-contrib','14','15','16']
    runs-on: ubuntu-latest
    env:
      IMG_NAME: aptible/postgresql
      REGISTRY: quay.io
      REPOSITORY: aptible/postgresql
      PUSH_REGISTRIES: $(REGISTRY) docker.io
      TAG: ${{ matrix.postgres }}

    steps:

    - uses: actions/checkout@v4
    
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    -
      name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMG_NAME }}
        tags:  ${{ matrix.postgres }}

    - name: Make Build
      run: make build

    - name: Run Tests
      run: make test

    - name: Make push
      if: github.event_name != 'pull_request'
      run: make push
