name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
      branches: 
      - "*"

jobs:
  build:
    strategy:
      matrix:
        postgres: ['9.5','9.5-contrib','9.5-pg_cron','9.6','9.6-contrib','10','10-contrib','10-pg_cron','11','11-contrib','12','12-contrib','13','13-contrib','14','15','16']
    runs-on: ubuntu-latest
    env:
      IMG_NAME: aptible/postgresql

    steps:

    - uses: actions/checkout@v4
    
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMG_NAME }}
        tags:  ${{ matrix.postgres }}

    - name: Make Build
      run: make build

    - name: Run Tests
      run: make test